### ISSUE TITLE
Running with Docker for Mac App

### ISSUE THREAD

**Issue by meerestier** [Jean-Beru/dockerfiles#3]
Hi there, I am trying to apply this to my Mac setup…

I run into 

```
docker run --rm -v .:/var/www/html -p 8080:80 --name akeneo_pim jeanberu/akeneo-pim

docker: Error response from daemon: create .: "." includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed.
```

Any ideas, why?

**Comment by Jean-Beru** [comment]
Hi.

My bad, relative path doesn't work with `docker` command. You have to put absolute path instead of `.`. I usually use `docker-compose` which accept this fomat. README.md has to be updated.

Thanks for you feedback!

**Comment by meerestier** [comment]
Sorry, which absolute path is required? I do not get which folder is supposed to be mounted here…

**Comment by Jean-Beru** [comment]
You have to mount the absolute path to your project. Your container must have access to your project in order to run it.
